version: '1'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=socialnetwork
      - MYSQL_PASSWORD=socialnetwork
      - MYSQL_DATABASE=socialnetwork
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --max_allowed_packet=20M
